### ISSUE TITLE
Feature Request: Custom Popups

### ISSUE THREAD

**Issue by campbeln** [arnauddri/ng-clustered-map#2]
Being able to define a simple popup, and preferably a rich popup, e.g. http://fusionmartialarts.com.au/classes.php

**Comment by arnauddri** [comment]
Hey, I just added it - you can checkout the doc and the demo page.

All you need to do is to add a 4th element to the array representing your pin:

``` javascript
$scope.markers = [[latitude, longitude, weight, popUpInnerHtml], .. ]
```
